### ISSUE TITLE
feat: Implement `plain` and `table` output

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/stackable-cockpit#142]
I'm wondering if we should rename the output type for `plain` to `table`.

```
stackablectl stacklet list --help

...

  -o, --output <OUTPUT_TYPE>
          [default: plain]

          Possible values:
          - plain: Print output formatted as plain text
          - json:  Print output formatted as JSON
          - yaml:  Print output formatted as YAML
```

I would expect `plain` to print out text with no decorations.

I discovered this because I was trying to find a way to print out the stacklet URLs without them breaking when my terminal width is small:

![image](https://github.com/stackabletech/stackable-cockpit/assets/10092581/10775b34-f501-4e3f-9b61-a0728aca8631)

_My workaround was to use `--output=yaml` to get unbroken clickable links in the terminal._

**Comment by fhennig** [comment]
"table" seems more appropriate :+1: 

maybe the "plain" setting could print a column layout without decorations and ignoring terminal width, similar to how kubectl prints it

**Comment by NickLarsenNZ** [comment]
I can make it look like this by just disabling the arrangement (ignoring terminal width) and table border characters.

```
 PRODUCT   NAME      NAMESPACE  ENDPOINTS                                   CONDITIONS                      
 opa       opa       default                                                Available, Reconciling, Running 
 superset  superset  default    external-http http://172.18.0.2:30232       Available, Reconciling, Running 
 trino     trino     default    coordinator-metrics 172.18.0.2:30392        Available, Reconciling, Running 
                                coordinator-https https://172.18.0.2:30416   
```

If the terminal is narrow, the text will wrap like so:

```
 PRODUCT   NAME      NAMESPACE  ENDPOINTS                                   CO
NDITIONS                      
 opa       opa       default                                                Av
ailable, Reconciling, Running 
 superset  superset  default    external-http http://172.18.0.2:30232       Av
ailable, Reconciling, Running 
 trino     trino     default    coordinator-metrics 172.18.0.2:30392        Av
ailable, Reconciling, Running 
                                coordinator-https https://172.18.0.2:30416   
```

I have also removed the padding between the endpoint name and URL in the plain output.

Some of the other commands output a lot of blank lines, so I need to look into the cause of that (it appears to be from descriptions). Some commands don't allow different output (like cache list) so I'm working on that too.
