### ISSUE TITLE
Add command for creating a debug container

### ISSUE THREAD

**Issue by nightkr** [stackabletech/stackable-cockpit#201]

**Comment by lfrancke** [comment]
The PR isn't merged, this ticket isn't closed but it is in Done.
What's the deal?

And can you please link to the documentation for this?

**Comment by sbernauer** [comment]
Seems like the PR is merged :thinking: Or what PR are you referring to?

**Comment by lfrancke** [comment]
It wasn't when I commented.

**Comment by sbernauer** [comment]
Alright, that makes sense :+1:

**Comment by nightkr** [comment]
Docs PR: https://github.com/stackabletech/stackable-cockpit/pull/227
